spring:
  application:
    name: pia-simulator
  jackson:
    serialization:
      write-dates-as-timestamps: false
  cloud:
    aws:
      region:
        static: ${AWS_REGION:eu-west-1}

pia:
  simulator:
    queue-name: ${PIA_SQS_PAYMENT_EVENTS_QUEUE:payment-events-queue}
    interval-ms: ${PIA_SIMULATOR_INTERVAL_MS:60000}
